# Generated by Django 3.2 on 2023-12-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231129_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmation_code',
            new_name='conf_code',
        ),
    ]
