# Generated by Django 3.2 on 2023-12-03 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20231203_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1500)], verbose_name='Год выпуска'),
        ),
    ]
