# Generated by Django 3.2 on 2023-12-03 14:35

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[reviews.models.validate_year], verbose_name='Год выпуска'),
        ),
    ]
