# Generated by Django 3.2 on 2023-12-03 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Ниже допустимого'), django.core.validators.MaxValueValidator(10, message='Выше допустимого')]),
        ),
    ]
