# Generated by Django 3.2 on 2023-11-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('id',)},
        ),
    ]
