# Generated by Django 3.2 on 2023-11-30 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0012_auto_20231129_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='autor',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='autor',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.user'),
            preserve_default=False,
        ),
    ]
