# Generated by Django 3.2 on 2023-11-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20231130_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='autor',
            new_name='author',
        ),
    ]
